### ISSUE TITLE
sh: mysql_config: command not found

### ISSUE THREAD

**Issue by sailsheep** [lyhapple/django-adminlte#30]
pip install -r requirement.txt 到安装mysql的时候就会报错
Collecting MySQL-python==1.2.5 (from -r requirement.txt (line 10))
  Using cached MySQL-python-1.2.5.zip
    Complete output from command python setup.py egg_info:
    sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/xx/ftb5d3rd7zsg620wkdydhq180000gn/T/pip-build-lao0vC/MySQL-python/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 43, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 25, in mysql_config
 raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found

**Comment by lyhapple** [comment]
你用的什么环境， 不是osx 或 linux吗？

**Comment by code-cookie** [comment]
我也是这样，linux环境下
